
import javax.swing.JLayeredPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jpTrangChu = new javax.swing.JPanel();
        javax.swing.JMenuBar jmMenu = new javax.swing.JMenuBar();
        javax.swing.JMenu jmWinMart = new javax.swing.JMenu();
        javax.swing.JMenuItem jmiNhanVien = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jmiKhachHang = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jmiSanPham = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jmiHoaDon = new javax.swing.JMenuItem();
        javax.swing.JMenu jmThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpTrangChuLayout = new javax.swing.GroupLayout(jpTrangChu);
        jpTrangChu.setLayout(jpTrangChuLayout);
        jpTrangChuLayout.setHorizontalGroup(
            jpTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jpTrangChuLayout.setVerticalGroup(
            jpTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jmWinMart.setText("WinMart");
        jmWinMart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jmiNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiNhanVien.setText("Nhân Viên");
        jmiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhanVienActionPerformed(evt);
            }
        });
        jmWinMart.add(jmiNhanVien);

        jmiKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiKhachHang.setText("Khách Hàng");
        jmWinMart.add(jmiKhachHang);

        jmiSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiSanPham.setText("Sản Phẩm");
        jmWinMart.add(jmiSanPham);

        jmiHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiHoaDon.setText("Hóa Đơn");
        jmWinMart.add(jmiHoaDon);

        jmMenu.add(jmWinMart);

        jmThoat.setText("Thoát");
        jmThoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmMenu.add(jmThoat);

        setJMenuBar(jmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhanVienActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }                      

    private static class QuanLyNhanVien {

        public QuanLyNhanVien() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
    }//GEN-LAST:event_jmiNhanVienActionPerformed
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

