USE [master]
GO


/****** Object:  Database [QLST_DB]     ******/
CREATE DATABASE [QLST_DB]
GO



USE [QLST_DB]
GO

/****** Object:  Table [dbo].[CUNGCAP]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUNGCAP](
	[MANCC] [char](7) NOT NULL,
	[MAHANG] [char](7) NOT NULL,
 CONSTRAINT [PK_CUNGCAP] PRIMARY KEY CLUSTERED 
(
	[MANCC] ASC,
	[MAHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SANPHAM]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MASANPHAM] [char](7) NOT NULL,
	[SOLUONG] [char](7) NOT NULL,
	[TENSANPHAM] [nvarchar](30) NULL,
	[GIANHAP] [money] NULL,
	[DONVITINH] [nvarchar](15) NULL,
	[TENNSX] [int] NULL,
	[GIABAN] [MONEY] NULL
	
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
UPDATE STATISTICS [dbo].[DMHANG] WITH ROWCOUNT = 2, PAGECOUNT = 2
GO

/****** Object:  Table [dbo].[DVT]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DVT](
	[DVT] [nvarchar](50) NULL
) ON [PRIMARY]

GO
UPDATE STATISTICS [dbo].[DVT] WITH ROWCOUNT = 2, PAGECOUNT = 1
GO


GO
/****** Object:  Table [dbo].[LOAIHANG]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAIHANG](
	[LOAI] [char](7) NOT NULL,
	[TENLOAI] [nvarchar](30) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
UPDATE STATISTICS [dbo].[LOAIHANG] WITH ROWCOUNT = 9, PAGECOUNT = 1
GO
/****** Object:  Table [dbo].[LOAITK]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAITK](
	[LOAITK] [int] NOT NULL,
	[MOTA] [char](30) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
UPDATE STATISTICS [dbo].[LOAITK] WITH ROWCOUNT = 3, PAGECOUNT = 1
GO
/****** Object:  Table [dbo].[NHASANXUAT]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TENNHASANXUAT](
	[TENNSX] [nvarchar](30) NULL,
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
UPDATE STATISTICS [dbo].[NHACUNGCAP] WITH ROWCOUNT = 7, PAGECOUNT = 1
GO
/****** Object:  Table [dbo].[NHANVIEN]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](7) NOT NULL,
	[CHUCVU] [int] NULL,
	[EMAIL] [char] (20) NOT NULL,
	[MATKHAU] [nvarchar] (20) NULL,
	[TENNV] [char](30) NULL,
	[GIOITINH] [bit] NULL
	[SODIENTHOAI] [char](10) NULL
	
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
UPDATE STATISTICS [dbo].[NHANVIEN] WITH ROWCOUNT = 7, PAGECOUNT = 1
GO

/****** Object:  Table [dbo].[TAIKHOAN]     ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[TENDANGNHAP] [nchar](20) NOT NULL,
	[LOAITK] [int] NULL,
	[MOTA] [char](30) NULL,
	[PASSWORD] [nchar](20) NULL
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[TENDANGNHAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT [dbo].[CUNGCAP] ([MANCC], [MAHANG]) VALUES (N'NCC0005', N'HH0001 ')
INSERT [dbo].[DMHANG] ([MAHANG], [LOAI], [NHOMHANG], [TENHANG], [GIABAN], [DVT], [TONBANLE], [TRANGTHAI], [TONKHO]) VALUES (N'HH0001 ', N'TP     ', N'4      ', N'Ca moi 3 Co gai', 10080.0000, N'Lon', 0, 1, 2200)
INSERT [dbo].[DMHANG] ([MAHANG], [LOAI], [NHOMHANG], [TENHANG], [GIABAN], [DVT], [TONBANLE], [TRANGTHAI], [TONKHO]) VALUES (N'HH0007 ', N'MP     ', N'4      ', N'Dau Goi Dau Rejoice', 7840.0000, N'Chai', 0, 0, 580)
INSERT [dbo].[DVT] ([DVT]) VALUES (N'Nghin dong')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'TP     ', N'Thuc Pham')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'GD     ', N'Gia dung')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'DT     ', N'Dien tu')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'X      ', NULL)
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'GK     ', N'Nuoc ngot')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'MP     ', N'My pham')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'VP     ', N'Van phong')
INSERT [dbo].[SANPHAM] ([MASANPHAM], [TENSANPHAM]) VALUES (N'MM     ', N'May mac')
INSERT [dbo].[LOAIHANG] ([LOAI], [TENLOAI]) VALUES (N'SU     ', N'Sua')
INSERT [dbo].[LOAITK] ([LOAITK], [MOTA]) VALUES (1, N'NHAN VIEN QUAN LY                    ')
INSERT [dbo].[LOAITK] ([LOAITK], [MOTA]) VALUES (2, N'KHACH HANG                           ')
INSERT [dbo].[LOAITK] ([LOAITK], [MOTA]) VALUES (3, N'Ban Hang                      ')
INSERT [dbo].[TENNHASANXUAT] ([TENNSX]) VALUES (N'NSX0001')
INSERT [dbo].[TENNHASANXUAT] ([TENNSX]) VALUES (N'NSX0002')
INSERT [dbo].[TENNHASANXUAT] ([TENNSX]) VALUES (N'NSX0003')
INSERT [dbo].[TENNHASANXUAT] ([TENNSX]) VALUES (N'NSX0004')
INSERT [dbo].[TENNHASANXUAT] ([TENNSX]) VALUES (N'NSX0005')
INSERT [dbo].[NHANVIEN] ([MANV], [CHUCVU],[EMAIL],[MATKHAU],[TENNV], [GIOITINH], [SODIENTHOAI]) VALUES (N'NV001  ',N'Quan ly        ',N'Tuanh12@gmail.com      ',N'TuAnh12      ', N'Nguyen Tu Anh                        ', N'NAM              ',N'0648382392       ' , NULL, NULL)
INSERT [dbo].[NHANVIEN] ([MANV], [CHUCVU],[EMAIL],[MATKHAU],[TENNV], [GIOITINH], [SODIENTHOAI])) VALUES (N'NV003  ',N'Ban hang      ',N'Hamy9966@gmail.com      ',N'Lehamy123      ', N'Le Ha My                        ', N'NU              ',N'0987365980       ' , NULL, NULL)
INSERT [dbo].[TAIKHOAN] ([TENDANGNHAP], [LOAITK],[MOTA], [PASSWORD]) VALUES (N'Hamy996        ,N'Ban Hang             ', 2, N'123456                                 ')
INSERT [dbo].[TAIKHOAN] ([TENDANGNHAP], [LOAITK],[MOTA], [PASSWORD]) VALUES (N'khachhang             ',N'KHACH HANG                 ', 3, N'12345                     ')
INSERT [dbo].[TAIKHOAN] ([TENDANGNHAP], [LOAITK],[MOTA], [PASSWORD]) VALUES (N'Admin         ,N'NHAN VIEN QUAN LY             ', 1, N'Admin                                     ')

SET ANSI_PADDING ON


ALTER TABLE [dbo].[SANPHAM] ADD  CONSTRAINT [PK_SANPHAM] PRIMARY KEY NONCLUSTERED 
(
	[MASANPHAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO




